title: Teah Github Blog # your name (or website title) here
logo: "C:\Users\teah4\OneDrive\Desktop\nlprocessor\logoMocha" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  I wonder How Our Brain Work? Thus I learn how data is processed.<br><br>
  <a href="https://www.linkedin.com/teah-trang-khong">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: 6Q9DZRFJ57
